name: Archive README

on:
  push:
    branches:
      - main # déclenchement sur le main

jobs:
  archive-readme:
    runs-on: ubuntu-latest

    steps:

      - name: Copy README.md to Q1_archive_README.md
        run: cp README.md Q1_archive_README.md

      - name: Configure git
        run: |
          git config user.name "zbilamouette"
          git config user.email "janotflorian@gmail.com"

      # Étape 4 : Ajouter le nouveau fichier et faire un commit
      - name: Commit changes
        run: |
          git add Q1_archive_README.md
          git commit -m "Add Q1_archive_README.md"

      # Étape 5 : Pousser les changements sur le dépôt
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
