name: Archive README

on:
  push:
    branches:
      - main # déclenchement sur le main

jobs:
  archive-readme:
    runs-on: ubuntu-latest

    steps:
          # verif du code
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Copy README.md to Q1_archive_README.md
        run: cp README.md Q1_archive_README.md

      - name: Commit et push le fichier
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "zbilamouette"
          git config --global user.email "florian.janot@univ-lehavre.fr"
          git add Q1_archive_README.md
          git commit -m "Ajout de Q1_archive_README.md"
          git push
