name: Archive README

on:
  push:
    branches:
      - main # déclenchement sur la branche main
permissions: read-all, write-all

jobs:
  archive-readme:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérification du code
      - name: Checkout repository
        uses: actions/checkout@v3
    
      # Étape 2 : Copier le fichier README.md
      - name: Copy README.md to Q1_archive_README.md
        run: cp README.md Q1_archive_README.md

      # Étape 3 : Configurer Git
      - name: Configure Git
        run: |
          git config --global user.name "zbilamouette"
          git config --global user.email "florian.janot@etu.univ-lehavre.fr"

      # Étape 4 : Commit et push
      - name: Commit et push le fichier
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Q1_archive_README.md
          git commit -m "Ajout de Q1_archive_README.md" || echo "Rien à commit"
          git push origin main || echo "Le push a échoué"
