name: Archive README

on:
  push:
    branches:
      - main # déclenchement sur la branche main

permissions: write-all # permission d'ecrire dans le repo

jobs:
  archive-readme:
    runs-on: ubuntu-latest # self-hosted

    steps:
      # vérif du code
      - name: Checkout repository
        uses: actions/checkout@v3
    
      # copier le fichier README.md
      - name: Copy README.md to Q1_archive_README.md
        run: cp README.md Q1_archive_README.md

      # configurer Git
      - name: Configure Git
        run: |
          git config --global user.name "zbilamouette"
          git config --global user.email "florian.janot@etu.univ-lehavre.fr"

      # commit et push
      - name: Commit et push le fichier
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Q1_archive_README.md
          git commit -m "Ajout de Q1_archive_README.md" || echo "Rien à commit"
          git push origin main || echo "Le push a échoué"
