name: Archive README 2

on:
  push:
    branches:
      - main # déclenchement sur la branche main

jobs:
  archive-readme:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérification du code
      - name: Checkout repository
        uses: actions/checkout@v3
    
        # Étape 3 : Créer le fichier Q2_archive_README.md
      - name: Create Q2_archive_README.md
        run: |
          echo "Nom : JANOT" > Q2_archive_README.md
          echo "Prénom : Florian" >> Q2_archive_README.md
          echo "Date et heure : ${{ env.time }}" >> Q2_archive_README.md
          echo "" >> Q2_archive_README.md
          echo "Contenu de README.md :" >> Q2_archive_README.md
          echo "" >> Q2_archive_README.md
          cat README.md >> Q2_archive_README.md

      # Étape 3 : Configurer Git
      - name: Configure Git
        run: |
          git config --global user.name "zbilamouette"
          git config --global user.email "florian.janot@etu.univ-lehavre.fr"

      # Étape 4 : Commit et push
      - name: Commit et push le fichier
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Q2_archive_README.md
          git commit -m "Ajout de Q2_archive_README.md" || echo "Rien à commit"
          git push origin main || echo "Le push a échoué"
