name: Archive Java Q3

on:
  push:
    branches:
      - main # déclenchement sur la branche main

permissions: write-all # permission d'ecrire dans le repo

jobs:
  archive-readme:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérification du code
      - name: Checkout repository
        uses: actions/checkout@v3
    
        # Étape 3 : Créer le fichier Q3_archive_java.txt
      - name: Create Q3_archive_java.txt
        run: |
          echo "Nom : JANOT" > Q3_archive_java.txt
          echo "Prénom : Florian" >> Q3_archive_java.txt
          echo "" >> Q3_archive_java.txt
          echo "Contenu de Q3.java :" >> Q3_archive_java.txt
          echo "" >> Q3_archive_java.txt
          cat Q3.java >> Q3_archive_java.txt

      # Étape 3 : Configurer Git
      - name: Configure Git
        run: |
          git config --global user.name "zbilamouette"
          git config --global user.email "florian.janot@etu.univ-lehavre.fr"

      # Étape 4 : Commit et push
      - name: Commit et push le fichier
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Q2_archive_README.md
          git commit -m "Ajout de Q3_archive_java.txt" || echo "Rien à commit"
          git push origin main || echo "Le push a échoué"
