name: Archive Java Q3

on:
  push:
    branches:
      - main # déclenchement sur la branche main

permissions: write-all # permission d'ecrire dans le repo

jobs:
  archive-readme:
    runs-on: ubuntu-latest # self-hosted

    steps:
      # vérification du code
      - name: Checkout repository
        uses: actions/checkout@v3
    
        # créer le fichier Q3_archive_java.txt
      - name: Create Q3_archive_java.txt
        run: |
          echo "Nom : JANOT" > Q3_archive_java.txt
          echo "Prénom : Florian" >> Q3_archive_java.txt
          echo "" >> Q3_archive_java.txt
          echo "Contenu de Q3.java :" >> Q3_archive_java.txt
          echo "" >> Q3_archive_java.txt
          cat Q3.java >> Q3_archive_java.txt

      # configurer Git
      - name: Configure Git
        run: |
          git config --global user.name "zbilamouette"
          git config --global user.email "florian.janot@etu.univ-lehavre.fr"

      # commit et push
      - name: Commit et push le fichier
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Q3_archive_java.txt
          git commit -m "Ajout de Q3_archive_java.txt" || echo "Rien à commit"
          git push origin main || echo "Le push a échoué"
