name: Archive Q5.java

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  archive-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current date and time
        id: datetime
        run: |
          DATE=$(date '+%d-%m-%Y-%H%M%S')
          echo "DATE=$DATE" >> $GITHUB_ENV

      - name: Create Q5_archive_date.txt
        run: |
          ARCHIVE_FILE="Q5_archive_$DATE.txt"
          echo "Nom: Florian Janot" > $ARCHIVE_FILE
          echo "" >> $ARCHIVE_FILE
          cat Q5.java >> $ARCHIVE_FILE
          echo "" >> $ARCHIVE_FILE
          wc -c < Q5.java >> $ARCHIVE_FILE
          echo "Nombre de lignes:" >> $ARCHIVE_FILE
          wc -l < Q5.java >> $ARCHIVE_FILE
          echo "Fichier créé : $ARCHIVE_FILE"

      - name: Verify if the archive file exists
        run: |
          echo "Vérification de l'existence du fichier $ARCHIVE_FILE"
          if [ -f "$ARCHIVE_FILE" ]; then
            echo "Le fichier $ARCHIVE_FILE a été créé avec succès."
          else
            echo "Le fichier $ARCHIVE_FILE n'a pas été créé."
            exit 1
          fi

      - name: List all Q5 archive files
        run: |
          echo "Liste des fichiers d'archive Q5 :"
          ls Q5_archive_*.txt

      - name: Configure Git
        run: |
          git config --global user.name "zbilamouette"
          git config --global user.email "florian.janot@etu.univ-lehavre.fr"

      - name: Commit and push archive file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Q5_archive_*.txt
          git commit -m "Ajout du fichier d'archive Q5"
          git push
