name: Archive Q6.java and Compare Differences

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  archive-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current date and time
        id: datetime
        run: |
          DATE=$(date '+%d-%m-%Y-%H%M%S')
          echo "DATE=$DATE" >> $GITHUB_ENV

      - name: Create Q6_archive_date.txt
        run: |
          ARCHIVE_FILE="Q6_archive_$DATE.txt"
          echo "Nom: Florian Janot" > $ARCHIVE_FILE
          echo "" >> $ARCHIVE_FILE
          cat Q6.java >> $ARCHIVE_FILE
          echo "" >> $ARCHIVE_FILE
          echo "Nombre de caracteres:" >> $ARCHIVE_FILE
          wc -c < Q6.java >> $ARCHIVE_FILE
          echo "Nombre de lignes:" >> $ARCHIVE_FILE
          wc -l < Q6.java >> $ARCHIVE_FILE

      - name: Compare with previous Q6 archive
        run: |
          LAST_ARCHIVE=$(ls Q6_archive_*.txt | sort | tail -n 2 | head -n 1)
          NEW_ARCHIVE="Q6_archive_$DATE.txt"
          if [ -f "$LAST_ARCHIVE" ]; then
            diff $LAST_ARCHIVE $NEW_ARCHIVE > Q6_différences.txt
          else
            echo "Aucun fichier précédent à comparer." > Q6_différences.txt
          fi

      - name: Configure Git
        run: |
          git config --global user.name "zbilamouette"
          git config --global user.email "florian.janot@etu.univ-lehavre.fr"

      - name: Commit and push archive and diff files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Q6_archive_*.txt Q6_différences.txt
          git commit -m "Ajout des fichiers d'archive et des différences"
          git push
